import { useEffect, useRef, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import ProgressBar from "./ProgressBar";
import UploadFormPreview from "./UploadFormPreview";

//
//  note for myself, you'll definitely forget how this component run
//  1. on input file -> if file types match setPreviewFile & setTempFile
//  2. preview image will appears and hidden img will be
//     rendered to the dom so the dimension can be saved with setFileDImension
//  3. if user click upload -> setFile(tempFile) then progress bar appears
//  4. when the upload process done, url will be generated by firebase storage,
//     then setFile to null and setIsDoneUploading to true
//  5. when isDoneUploading set to true, the state cleanup function will run,
//     then setIsDoneUpload to null again after 5 second to hide the success alert
//

function UploadForm() {
  const [previewFile, setPreviewFile] = useState(null);
  const [fileDimension, setFileDimension] = useState([]);
  const [tempFile, setTempFile] = useState(null);
  const [file, setFile] = useState(null);
  const [error, setError] = useState(null);
  const [isUploading, setIsUploading] = useState(null);
  const [imageData, setImageData] = useState({});

  const types = ["image/png", "image/jpeg"];
  const uploadBtn = useRef(null);

  const handleInputFile = (e) => {
    const selectedFile = e.target.files[0];

    // make a new image object to contain the preview and it's dimension
    // if user cancel the selection file then the next function will not run
    if (selectedFile) {
      const img = new Image();
      img.src = URL.createObjectURL(e.target.files[0]);

      if (selectedFile && types.includes(selectedFile.type)) {
        setPreviewFile(img.src);
        setTempFile(selectedFile);
        setError(null);
      } else {
        setPreviewFile(null);
        setError(
          "Please use png or jpg only to not make things complicated 😢"
        );
      }
    } else {
      // reset the previewFile if user cancel the selection file
      setPreviewFile(null);
    }
  };

  const handleLoadPreview = (e) => {
    setFileDimension([e.target.width, e.target.height]);
  };

  const handleUpload = (selectedTags, isAnonymous) => {
    const tempImageData = {
      selectedTags: selectedTags,
      isAnonymous: isAnonymous,
      width: fileDimension[0],
      height: fileDimension[1],
    };
    setImageData(tempImageData);
    setFile(tempFile);
  };

  // cleanup state when finished uploading
  useEffect(() => {
    if (isUploading !== null) {
      setPreviewFile(null);
      setFileDimension(null);
      setTempFile(null);
      setFile(null);
      uploadBtn.current.value = "";

      // show success alert for 5 second
      setTimeout(() => {
        setIsUploading(null);
      }, 5000);
    }
  }, [isUploading]);

  return (
    <div className="flex justify-center mx-8 mt-5 md:mx-auto">
      <div className="grid w-full place-items-center">
        {/* input */}
        <div>
          <form>
            <input
              hidden
              type="file"
              onChange={handleInputFile}
              ref={uploadBtn}
            />
          </form>
          <button
            className="inputBtn"
            onClick={() => uploadBtn.current.click()}
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="w-6 h-6"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M12 6v6m0 0v6m0-6h6m-6 0H6"
              />
            </svg>
          </button>
        </div>

        {/* output */}
        <div data-name="softRed" className="w-full mt-10 md:max-w-3xl">
          {error && (
            <span className="px-4 py-2 text-red-400 bg-red-100 rounded">
              {" "}
              {error}{" "}
            </span>
          )}

          {/* preview image */}
          <AnimatePresence>
            {previewFile && (
              <UploadFormPreview
                previewFile={previewFile}
                handleLoadPreview={handleLoadPreview}
                handleUpload={handleUpload}
                fileName={tempFile.name}
              />
            )}
          </AnimatePresence>

          {/* progress bar */}
          <AnimatePresence>
            {file && (
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="w-full mt-5"
              >
                <ProgressBar
                  selectedTags={imageData.selectedTags}
                  isAnonymous={imageData.isAnonymous}
                  file={file}
                  width={imageData.width}
                  height={imageData.height}
                  setFile={setFile}
                  setIsUploading={setIsUploading}
                />
              </motion.div>
            )}
          </AnimatePresence>

          {/* status only appear when isUploading state not null */}
          <AnimatePresence>
            {isUploading && (
              <motion.span
                transition={{ ease: "easeInOut" }}
                initial={{ opacity: 0, y: "-100vh" }}
                animate={{ opacity: 1, y: "0vh" }}
                exit={{ opacity: 0, y: "-100vh" }}
                onClick={() => setIsUploading(null)}
                className="fixed px-5 py-3 text-blue-400 bg-blue-100 rounded cursor-pointer top-5 right-5"
              >
                Upload Success
              </motion.span>
            )}
          </AnimatePresence>
        </div>
      </div>
    </div>
  );
}

export default UploadForm;
