import Head from "next/head";
import { useEffect } from "react";
import UploadForm from "../components/ui/UploadForm";
import ImageList from "../components/UI/ImageList";

export default function Home() {
  return (
    <>
      <Head>
        <title>Splash</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <div className="text-center">
          <h1 className="text-4xl font-bold text-gray-600">Splash It</h1>
          <p className="mt-5 text-base text-gray-500">
            an Unsplash photo gallery clone, because why not
          </p>
        </div>
        <div className="flex justify-center mt-5">
          <UploadForm />
        </div>
        <div className="mt-5">
          <ImageList />
        </div>
      </section>
    </>
  );
}
