import Head from "next/head";
import { useEffect } from "react";
import UploadForm from "../components/UI/UploadForm";
import ImgList from "../components/UI/ImgList";
import Title from "../components/UI/Title";
import { motion, AnimatePresence } from "framer-motion";

export default function Home() {
  return (
    <>
      <Head>
        <title>Splash</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <Title />
        <UploadForm />
        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="w-full">
          <ImgList />
        </motion.div>
      </section>
    </>
  );
}
